# Generated by Django 4.0 on 2023-01-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='profession',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
