# Generated by Django 4.0 on 2023-01-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reunion', '0003_remove_membre_nom_alter_membre_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='is_comissaire',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='is_membre',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='is_president',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='is_secretaire',
        ),
    ]
